name: Python 3.9

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-test.yml
    with:
      python-version: '3.9'